phrases = {
	'also known as' : 'aka',
	'as far as i know' : 'AFAIK',
	'as soon as possible' : 'asap',
	'at the moment' : 'atm',
	'be back later' : 'bbl',
	'be back' : 'brb',
	'be right back' : 'brb',
	'by the way' : 'btw',
	'correct me if i\'m wrong' : 'CMIIW',
	'don\'t give a fuck' : 'DGAF',
	'for what it\'s worth' : 'FWIW',
	'for your info' : 'fyi',
	'for your information' : 'fyi',
	'fuck my life' : 'fml',
	'good luck' : 'gl',
	'good morning' : 'gm',
	'got to go' : 'g2g',
	'gotta go' : 'g2g',
	'happy birthday' : 'hb',
	'how about you' : 'hbu',
	'how are you' : 'how r u',
	'i don\'t care' : 'idc',
	'i don\'t even know' : 'idek',
	'i don\'t fucking know' : 'idfk',
	'i don\'t give a fuck' : 'idgaf',
	'i don\'t know' : 'idk',
	'i know right' : 'ikr',
	'i love you too' : 'ily2',
	'i love you' : 'ily',
	'i miss you too' : 'imy2',
	'i miss you' : 'imy',
	'i see you' : 'icu',
	'if i recall correctly' : 'IIRC',
	'if i remember correctly' : 'IIRC',
	'in my honest opinion' : 'imho',
	'in my humble opinion' : 'imho',
	'in my opinion' : 'imo',
	'in real life' : 'IRL',
	'instant message' : 'im',
	'just kidding' : 'jk',
	'long distance relationship' : 'ldr',
	'no problem' : 'np',
	'not much' : 'nm',
	'nothing much' : 'nm',
	'oh my god' : 'omg',
	'oh my gosh' : 'omg',
	'on my way' : 'omw',
	'on the other hand' : 'OTOH',
	'one of my followers' : 'OOMF',
	'see ya' : 'cya',
	'see you' : 'c u',
	'talk to you later' : 'ttyl',
	'thank you' : 'ty',
	'to be honest' : 'tbh',
	'what are you doing' : 'wyd',
	'what the fuck' : 'wtf',
	'what the heck' : 'wth',
	'what the hell' : 'wth',
	'what\'s up' : 'sup',
	'why are you' : 'yru'
}


words = {
	'\'d' : 'd',
	'\'ll' : 'll',
	'\'m' : 'm',
	'\'re' : 're',
	'\'s' : 's',
	'\'ve' : 've',
	'2009' : '09',
	'about' : 'ab',
	'actually' : 'rly',
	'after' : 'aftr',
	'again' : 'agn',
	'already' : 'alrdy',
	'amazing' : 'gr8',
	'and' : '&',
	'another' : 'anoth',
	'any' : 'ne',
	'anyone' : 'ne1',
	'anything' : 'nething',
	'anyway' : 'neway',
	'are' : 'r',
	'around' : 'arnd',
	'at' : '@',
	'awesome' : 'awesum',
	'baby' : 'bby',
	'back' : 'bk',
	'be' : 'b',
	'beautiful' : 'pretty',
	'because' : 'bc',
	'before' : 'b4',
	'being' : 'bein',
	'better' : 'btr',
	'between' : 'btw',
	'birthday' : 'bday',
	'black' : 'blk',
	'book' : 'bk',
	'both' : 'bth',
	'boyfriend' : 'bf',
	'break' : 'brk',
	'brother' : 'bro',
	'business' : 'biz',
	'but' : 'bt',
	'can\'t' : 'cant',
	'check' : 'chk',
	'coming' : 'cmng',
	'computer' : 'cpu',
	'crazy' : 'crzy',
	'dinner' : 'dnnr',
	'doing' : 'doin',
	'dont' : 'dnt',
	'down' : 'dwn',
	'eating' : 'eatin',
	'enough' : 'enuf',
	'ever' : 'evr',
	'every' : 'evry',
	'everyone' : 'evry1',
	'everything' : 'evrythg',
	'excited' : 'xcited',
	'facebook' : 'fb',
	'family' : 'fam',
	'first' : '1st',
	'follow' : 'flw',
	'for' : '4',
	'forward' : '4wd',
	'friday' : 'fri',
	'from' : 'frm',
	'getting' : 'gttng',
	'going' : 'gng',
	'good' : 'gud',
	'goodbye' : 'bye',
	'great' : 'gr8',
	'haha' : 'ha',
	'half' : '1/2',
	'happen' : 'hpn',
	'happened' : 'hpn',
	'happy' : ':)',
	'hate' : 'h8',
	'having' : 'hvng',
	'help' : 'hlp',
	'hey' : 'hi',
	'high' : 'hi',
	'hour' : 'hr',
	'hours' : 'hrs',
	'important' : 'imp',
	'information' : 'info',
	'interesting' : 'cool',
	'internet' : 'net',
	'into' : 'n2',
	'just' : 'jst',
	'know' : 'no',
	'late' : 'l8',
	'later' : 'l8r',
	'like' : 'lk',
	'listening' : 'listenin',
	'little' : 'lil',
	'lol' : 'ha',
	'long' : 'lng',
	'looking' : 'lookn',
	'love' : '<3',
	'making' : 'makn',
	'maybe' : 'mayb',
	'meeting' : 'mtng',
	'message' : 'msg',
	'might' : 'mite',
	'minutes' : 'mins',
	'monday' : 'mon',
	'money' : '$$$',
	'morning' : 'AM',
	'n\'t' : 'nt',
	'never' : 'nvr',
	'nevermind' : 'nvm',
	'new' : 'nw',
	'next' : 'nxt',
	'night' : 'nite',
	'nothing' : 'nth',
	'now' : 'nw',
	'oh' : 'o',
	'ok' : 'k',
	'once' : '1ce',
	'one' : '1',
	'online' : 'OL',
	'or' : '/',
	'other' : 'othr',
	'page' : 'pg',
	'part' : 'pt',
	'people' : 'ppl',
	'photo' : 'pic',
	'playing' : 'playin',
	'please' : 'pls',
	'probably' : 'prob',
	'Rate' : 'r8',
	'reading' : 'readin',
	'ready' : 'rdy',
	'really' : 'rly',
	'reply' : 'rply',
	'right' : 'rite',
	'rock' : 'rck',
	'room' : 'rm',
	'running' : 'runnin',
	'school' : 'skl',
	'see' : 'c',
	'send' : 'snd',
	'seriously' : 'srsly',
	'should' : 'shud',
	'sister' : 'sis',
	'skate' : 'sk8',
	'sleep' : 'slp',
	'snow' : 'snw',
	'some' : 'sum',
	'someone' : 'sum1',
	'something' : 'sth',
	'sorry' : 'sry',
	'start' : 'strt',
	'started' : 'strtd',
	'story' : 'stry',
	'sunday' : 'sun',
	'take' : 'tk',
	'taking' : 'tkn',
	'talking' : 'tlkn',
	'than' : 'thn',
	'thank' : 'thnk',
	'thanks' : 'thx',
	'that' : 'tht',
	'them' : 'thm',
	'then' : 'thn',
	'think' : 'thnk',
	'thinking' : 'thnkn',
	'this' : 'ths',
	'though' : 'tho',
	'through' : 'thru',
	'to' : '2',
	'today' : '2day',
	'tomorrow' : '2mr',
	'tonight' : '2nite',
	'too' : '2',
	'totally' : 'ttly',
	'trying' : 'tryn',
	'tweet' : 'twt',
	'tweets' : 'twts',
	'twitter' : 'twtr',
	'two' : '2',
	'Unfortunately' : 'unf',
	'until' : 'til',
	'using' : 'usng',
	'very' : 'vry',
	'video' : 'vid',
	'wait' : 'w8',
	'waiting' : 'w8n',
	'wants' : 'wnts',
	'watching' : 'watchin',
	'weather' : 'wthr',
	'website' : 'site',
	'week' : 'wk',
	'weekend' : 'wknd',
	'welcome' : 'wc',
	'went' : 'wnt',
	'what' : 'wat',
	'whatever' : 'w/e',
	'when' : 'whn',
	'where' : 'whr',
	'while' : 'whle',
	'why' : 'y',
	'with' : 'w/',
	'without' : 'w/o',
	'won\'t' : 'wont',
	'wonder' : 'wndr',
	'wondering' : 'wonderin',
	'word' : 'wrd',
	'work' : 'wrk',
	'working' : 'wrkn',
	'world' : 'wrld',
	'would' : 'wud',
	'writing' : 'wrtg',
	'yeah' : 'ya',
	'year' : 'yr',
	'years' : 'yrs',
	'yesterday' : 'yda',
	'you\'re' : 'ur',
	'you' : 'u',
	'your' : 'ur'
}